### ISSUE TITLE
Can't  build  Android 

### ISSUE THREAD

**Issue by xuanson97hg** [anilsathyan7/Portrait-Segmentation#7]
i can't not fix  error

 Build file '/Users/sondx/Desk/FirstTime/demo_android/Portrait-Segmentation-master/android/SegMe_V1/app/build.gradle' line: 50
A problem occurred evaluating project ':app'.
> Cannot invoke method apply() on null object

when i try to build android app

**Comment by anilsathyan7** [comment]
I hope you got the error when you tried to build the project in android studio without any modification??
Ensure that you update the plugins and android studio....
Please post the entire error log ...

**Comment by khangdm** [comment]
@anilsathyan7 i have err when launch app. it err before 
`    Process: android.example.com.tflitecamerademo3, PID: 9259
    java.lang.NoSuchMethodError: No virtual method getContext()Landroid/content/Context; in class Lcom/example/android/tflitecamerademo4/Camera2BasicFragment; or its super classes (declaration of 'com.example.android.tflitecamerademo4.Camera2BasicFragment' appears in /data/app/android.example.com.tflitecamerademo3-2/base.apk:classes2.dex)
        at com.example.android.tflitecamerademo4.Camera2BasicFragment.onViewCreated(Camera2BasicFragment.java:577)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:908)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
        at android.app.BackStackRecord.run(BackStackRecord.java:834)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1462)
        at android.app.Activity.performStart(Activity.java:6100)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2383)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
        at android.app.ActivityThread.access$900(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5408)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)`
i can't not fix err.
